on:
  schedule:
  - cron: "0 0 1 * *"
  workflow_dispatch:
jobs:
    repo-sync:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: sync
          run: |
            git fetch --all
            git diff --binary main test_branch > ./patch.patch
            git apply ./patch.patch
